# Generated by Django 5.0.4 on 2024-04-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_simulator', '0004_remove_cat_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='state',
            field=models.TextField(default='normal'),
        ),
    ]
