# Generated by Django 5.0.4 on 2024-04-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_simulator', '0005_cat_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='state',
            field=models.TextField(default='happy'),
        ),
    ]
